name: Proxy Guncelleyici

on:
  schedule:
    # Her saat başı otomatik çalışmasını tetikler
    - cron: '0 * * * *'
  workflow_dispatch: # İstediğimizde elle tetikleme butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4 # v3 yerine güncel v4 yaptık

      - name: Python Kurulumu
        uses: actions/setup-python@v5 # v4 yerine güncel v5 yaptık
        with:
          python-version: '3.x' # Buradaki yazım hatasını 'python-version' olarak düzelttik

      - name: Gerekli Paketleri Yukle
        run: pip install requests

      - name: Scraper Kodunu Calistir
        run: python scraper.py

      - name: Guncel Listeyi Depoya Yukle (Commit)
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add proxy_list.txt || true
          git commit -m "Proxy listesi otomatik guncellendi" || true
          git push || true
          
